### ISSUE TITLE
Please i want to know how can I use the command "and" on algogo on my android tablet.???

### ISSUE THREAD

**Issue by geoachi** [Skyost/Algogo#1]
**What were you doing when the error occurred ?**
I was doing...

**OS version and architecture (ex. Windows 8.1 - 64 bits) :**
 -  bits

**Java version and architecture (ex. Java 1.7.0_60 - 64 bits) :**
Java  -  bits.

**Stacktrace (the stacktrace obtained when the error occurred) :**
Paste it here.

*Be sure to include any additional information you have !
Thank you very much ;)*

**Comment by Skyost** [comment]
https://github.com/Skyost/Heartbeat#supported-operators

And operator : &&.
