### ISSUE TITLE
Report an issue

### ISSUE THREAD

**Issue by asmyoussof** [Skyost/Algogo#2]
Hello,
i want to signal here (in my opinnion) that the <---- is inversed in your program Algogo
in my course with student i use as this 
     variable  <-----   (expression)
will it be possible to invert it ? (for user preference)

tank you in Advance

**Comment by Skyost** [comment]
Hey,

I will do a massive rewrite of the program so yes, no problem ! :wink:

**Comment by Skyost** [comment]
Done !
